# Generated by Django 4.1.2 on 2022-10-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonips_student', '0002_alter_student_admission_date_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
