# Generated by Django 4.1.4 on 2023-02-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='current',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='current',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
