# Generated by Django 4.1.3 on 2023-02-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0003_alter_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
